apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: {{ .Values.appName }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.appName }}
  ports:
    {{- with .Values.service }}
    - port: {{ .port }}
      targetPort: {{ .port }}
    {{- end }}

